FROM ubuntu:14.04
python2.7

BWA_PATH = {
    "0.7.7": "/usr/local/bin/bwa0.7.7",
    "0.7.10": "/usr/local/bin/bwa0.7.10"
}

SAMTOOLS_PATH = {
    "0.1.19": "/usr/local/bin/samtools-0.1.19/samtools",
    "1.0": "/usr/local/bin/samtools-1.0/bin/samtools"
}
TRIMMOMATIC_PATH = "/usr/local/bin/Trimmomatic-0.36/trimmomatic-0.36.jar"
