version: '3.1'

services:
  mapper:
    image: mapping
    volumes:
      - /Users/idan/Documents/dockerFiles/mapping:/tmp/container
  post_processor:
    image: post-mapping
    volumes:
      - /Users/idan/Documents/dockerFiles/mapping:/tmp/container  
  filter:
    image: filter_qc
    volumes:
      - /Users/idan/Documents/dockerFiles/mapping:/tmp/container
  xcor:
    image: xcor
    volumes:
      - /Users/idan/Documents/dockerFiles/mapping:/tmp/container
